import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// create an API object called searchApi which
// will contain (i) where in our store we'll
// save our data; (ii) what url to use (iii)
// all of the endpoints we can get
export const searchApi = createApi({
  // save data within a search container in our store
  reducerPath: "",
  baseQuery: fetchBaseQuery({
    baseUrl: "http://localhost:8000",
  }),
  // setup tag for searches
  tagTypes: ["Search"],
  // use the endpoints function, which takes a
  // builder object and creates each of our endpoints
  endpoints: (builder) => ({
    // return the methods that are available to
    // interact with the API
    createSearch: builder.mutation({
      query: (data) => ({
        url: "/search/create",
        body: {
          owner: 1,
          participant_count: 1,
        },
        method: "post",
      }),
    }),
    getSearch: builder.query({
      // define a query function to return
      // the endpoints
      query: () => "search/${search_id}/options",
      providesTags: ["Search"],
    }),
  }),
});

// export hooks generated by the builder
export const { useGetSearchQuery, useCreateSearchMutation } = searchApi;
